// import { Inter} from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider"
// import Header from "@/components/header";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";
// import { Toaster } from "sonner";

// const inter=Inter({subsets:["latin"]});//font

// export const metadata = {
//   title: "AI  Carrer Coach",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider appearance={{
//       baseTheme:dark,
//     }}>
//       <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${inter.className}`}
//       >
//         <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {/* header */}
//             <Header/>

//             <main className="min-h-screen">{children}</main>
//             <Toaster richColors/>

//             <footer className="bg-muted/50 py-12">
//               <div className="container mx-auto px-4 text-center text-gray-200">
//                 <p>Made with love ❤️ by Sanjay</p>
//               </div>
//             </footer>
//           </ThemeProvider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] }); // font

export const metadata = {
  title: "AI Career Coach - Your Path to Success",
  description:
    "Boost your career with personalized AI guidance, interview coaching, and professional development tools.",
  keywords:
    "AI career coach, job interview prep, resume builder, career guidance, professional development",
  openGraph: {
    title: "AI Career Coach - Your Path to Success",
    description:
      "Boost your career with personalized AI guidance, interview coaching, and professional development tools.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Career Coach - Your Path to Success",
    description:
      "Boost your career with personalized AI guidance, interview coaching, and professional development tools.",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#3b82f6",
          colorBackground: "#0f172a",
          colorInputBackground: "#1e293b",
          colorInputText: "#f8fafc",
        },
        elements: {
          formButtonPrimary: "btn-modern-primary",
          card: "glass-strong rounded-2xl border-white/10",
          headerTitle: "gradient-text-primary",
          socialButtonsBlockButton:
            "glass border-white/20 hover:glass-strong",
          formFieldInput:
            "glass-subtle border-white/20 focus:border-blue-400",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin=""
          />
        </head>
        <body className={`${inter.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            forcedTheme="dark"
          >
            {/* Enhanced Header */}
            <Header />

            {/* Main Content with Enhanced Background */}
            <main className="min-h-screen relative">
              {/* Global Background Effects */}
              <div className="fixed inset-0 z-0 pointer-events-none">
                <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-900/10 to-slate-900" />
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse" />
                <div
                  className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse"
                  style={{ animationDelay: "2s" }}
                />
              </div>

              {/* Content */}
              <div className="relative z-10">{children}</div>
            </main>

            {/* Enhanced Toaster */}
            <Toaster
              richColors
              position="top-right"
              toastOptions={{
                style: {
                  background: "rgba(15, 23, 42, 0.9)",
                  backdropFilter: "blur(12px)",
                  border: "1px solid rgba(255, 255, 255, 0.1)",
                  color: "#f8fafc",
                },
              }}
            />

            {/* Enhanced Footer */}
            <footer className="relative z-10 glass-subtle border-t border-white/10 py-12 mt-20">
              <div className="container mx-auto px-4">
                <div className="grid md:grid-cols-4 gap-8 mb-8">
                  {/* Company Info */}
                  <div className="md:col-span-2">
                    <h3 className="text-2xl font-bold gradient-text-primary mb-4">
                      AI Career Coach
                    </h3>
                    <p className="text-slate-300 mb-4 leading-relaxed">
                      Empowering professionals worldwide with AI-driven career
                      guidance, interview preparation, and personalized growth
                      strategies.
                    </p>
                    <div className="flex space-x-4">
                      <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
                      <span className="text-sm text-slate-400">
                        24/7 AI Support Available
                      </span>
                    </div>
                  </div>

                  {/* Quick Links */}
                  <div>
                    <h4 className="text-lg font-semibold text-white mb-4">
                      Quick Links
                    </h4>
                    <ul className="space-y-2">
                      <li>
                        <Link
                          href="/dashboard"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Dashboard
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/resume"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Resume Builder
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/interview"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Interview Prep
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/ai-cover-letter"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Cover Letters
                        </Link>
                      </li>
                    </ul>
                  </div>

                  {/* Support */}
                  <div>
                    <h4 className="text-lg font-semibold text-white mb-4">
                      Support
                    </h4>
                    <ul className="space-y-2">
                      <li>
                        <Link
                          href="/help"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Help Center
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/contact"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Contact Us
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/privacy"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Privacy Policy
                        </Link>
                      </li>
                      <li>
                        <Link
                          href="/terms"
                          className="text-slate-300 hover:text-blue-400 transition-colors"
                        >
                          Terms of Service
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>

                {/* Copyright */}
                <div className="pt-8 border-t border-white/10 flex flex-col md:flex-row justify-between items-center">
                  <div className="text-slate-400 text-center md:text-left mb-4 md:mb-0">
                    <p className="flex items-center justify-center md:justify-start">
                      Made with
                      <span className="mx-1 text-red-400 animate-pulse">
                        ❤️
                      </span>
                      by
                      <span className="ml-1 gradient-text-primary font-semibold">
                        Sanjay
                      </span>
                    </p>
                  </div>
                  <div className="text-slate-400 text-sm">
                    © 2024 AI Career Coach. All rights reserved.
                  </div>
                </div>
              </div>

              {/* Decorative Elements */}
              <div className="absolute top-0 left-0 w-full h-px gradient-tech-primary opacity-50" />
              <div className="absolute -top-10 left-1/2 transform -translate-x-1/2 w-20 h-20 bg-blue-500/5 rounded-full blur-xl" />
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
